import type { Metadata } from "next";
import "./globals.css";

import localFont from 'next/font/local'
import Footer from "@/components/Footer";



const myFont = localFont({
  src: './loos light.otf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
     
        {children}
        
        
        </body>

    </html>
  );
}
